### ISSUE TITLE
Beta score threshold

### ISSUE THREAD

**Issue by Yiguan** [ksiewert/BetaScan#1]
Hi,
Very impressive method to detect balancing selection. I am trying to use it on the drosophila data.
I wonder if there exists a threshold for Beta score, above which an allele can be considered under balancing selection?
Thanks!

**Comment by ksiewert** [comment]
Great question! Unfortunately, like with most summary statistics, there's no way to know what the significance cut-off should be without additional information.

If you're able to, I would do genetic simulations under parameters that are realistic for drosophila. Then you can look at the distribution of Beta under neutrality, and figure out what you want your significance cut-off to be based on that.

If you don't want to do that, then it's pretty accepted in the field to just do an arbitrary percentage cut-off like top .1% or .5%.

**Comment by ksiewert** [comment]
Also, sorry it took me a few days to respond. My github settings weren't quite right, so it didn't e-mail me a notification. But I fixed them now, so I should be quicker with responding!
