### ISSUE TITLE
input file

### ISSUE THREAD

**Issue by pengyan19** [ksiewert/BetaScan#12]
Hello,I meet some question when i install glactools, can you provide some script to transform VCF to SNPfreq file,thanks

**Comment by ksiewert** [comment]
Hello, I am on maternity leave right now, so will be unable to provide much support. I would see if the awk command in [this question](https://github.com/ksiewert/BetaScan/wiki/Q&A#i-have-frequency-information-i-calculated-using-the---freq-command-in-vcftools-and-the---derived-flag-if-im-using-the-unfolded-betascan-how-do-i-convert-the-vcf-output-format-to-the-betascan-output-format) in the FAQ is helpful.
