### ISSUE TITLE
Error, missing data in the EPO file

### ISSUE THREAD

**Issue by jaesoonpark** [ksiewert/BetaScan#13]
Hello. 

I have an issue with calling ancestral alleles. 

The command line was same as the tutorial:
glactools vcfm2acf --onlyGT --epo all.epo.gz --fai human_g1k_v37.fasta.fai test.vcf > test.acf.gz 

The error message was 
**Error, missing data in the EPO file**

Could you explain what this means?

Thanks.

**Comment by ksiewert** [comment]
Hello,
I would talk to Gabriel, the creator of glactools package, about this error. I'm on maternity leave so can't provide assistance right now, and he's probably the best person to talk to regardless.

Best,
Katie
