### ISSUE TITLE
How to calculate the theta and Watterson's theta?

### ISSUE THREAD

**Issue by SC-Duan** [ksiewert/BetaScan#15]
Hi, I'm trying to calculate B2 using Betascan. This needs the theta value as a parameter, and how should I calculate it based on vcf file or beta input file? if I set DivTime parameter, this also need the 4Neu in BALLET. Thank you!

**Comment by ksiewert** [comment]
Hello! The estimation of the divergence time between two species is outside of the scope of the BetaScan toolkit. If you're not able to calculate it using other means, I recommend just using the B1 statistic.

**Comment by ksiewert** [comment]
Hello! If you're not comfortable estimating theta and the DivTime for your species isn't previously known, it might be worth just using the original Beta 1 statistic. That way you don't need theta or the DivTime. if you do really want to use B2, then I would get regions of the genome that you think are neutrally evolving, and calculate Watterson's theta on them.

**Comment by SC-Duan** [comment]
Thanks for your reply. I just want to test the B2 results and I request the source code from Achaz to calculate the theta  and have not heard back yet. Are there some softs can do it? Thank you very much!
