### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by owfh** [ksiewert/BetaScan#16]
when I use --freq of vcftools, then "awk -F "\t|:" '(NR>1) && ($8!='0') && ($8!='1') && ($3=='2') {OFS="\t"; print$2,$8*$4,$4}' chr5.southAmerica.frq > chr5.southAmerica.frq.txt" 
and "python betascan.py -i chr5.USAMS.frq.txt > chr5.USAMS.betascore" count one chromosome of ten individuals
the fllowing promblem occour:
Traceback (most recent call last):
  File "betascan.py", line 613, in <module>
    main()
  File "betascan.py", line 529, in main
    freq = freqCount/sampleN
ZeroDivisionError: float division by zero

**Comment by ksiewert** [comment]
Hello! It sounds like for some reason the sample size at one of your SNPs is 0. I would look at your chr5.southAmerica.frq.txt file and see if this is the case. If it is, I would remove any SNP with a sample size of 0.

**Comment by owfh** [comment]
Thank you very much for your reply. I used to make batascan with selected sites of two populations&nbsp; sweep selection without any problem, but now I make batascan with one population, and the SNPs is 0. The attachment&nbsp;is my chr5.southAmerica.frq.txt&nbsp;file，Trouble you！


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ksiewert/BetaScan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月8日(星期五) 上午7:53
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [ksiewert/BetaScan] ZeroDivisionError: float division by zero (Issue #16)





 
Hello! It sounds like for some reason the sample size at one of your SNPs is 0. I would look at your chr5.southAmerica.frq.txt file and see if this is the case. If it is, I would remove any SNP with a sample size of 0.

**Comment by owfh** [comment]
Thank you very much for your reply. I used to make batascan with selected sites of two populations&nbsp; sweep selection without any problem, but now I make batascan with one population, and the SNPs is 0. The&nbsp;attachment&nbsp;is my&nbsp;chr5.southAmerica.frq.txt&nbsp;file，Trouble you！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ksiewert/BetaScan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月8日(星期五) 上午7:53
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [ksiewert/BetaScan] ZeroDivisionError: float division by zero (Issue #16)





 
Hello! It sounds like for some reason the sample size at one of your SNPs is 0. I would look at your chr5.southAmerica.frq.txt file and see if this is the case. If it is, I would remove any SNP with a sample size of 0.
