### ISSUE TITLE
the value of Beta1*_std is miss

### ISSUE THREAD

**Issue by HengLiang1993** [ksiewert/BetaScan#17]
Hi
I run the code: python2 BetaScan.py -i output.beta.txt.gz -onewin -std -theta 0.157 -fold  -o betascores-std.txt, and the result show as:
Position	Beta1*	Beta1*_std
315639.0 -0.761294
315663.0	0.829734
315677.0	1.213546
315681.0	-0.746679
315685.0	1.253881
315686.0	1.159774
315689.0	0.97459
315690.0	1.25847
315705.0	1.256603
315715.0	1.249427
315725.0	-0.893911
315740.0	0.600665
315953.0	1.309721
316007.0	-0.764854
316008.0	1.27593

The value of Beta1*_std is miss.Only show the value of Beta1*.

Best

Heng

**Comment by ksiewert** [comment]
Hello. Sorry for the delayed response. If you wouldn't mind posting a screenshot of your input file around this genomic position, as well as a screenshot of the results file, that would be helpful.

**Comment by HengLiang1993** [comment]
Hi
My input file is;
zcat output.beta.txt.gz | head
315639	152	308
315663	18	330
315677	6	338
315681	162	338
315685	4	338
315686	8	338
315689	14	342
315690	1	344
315705	2	348
315715	1	350

**Comment by ksiewert** [comment]
Hello. Only Beta1*_std should be outputted when the -onewin command is used (see the explanation of the -onewin command [here](https://github.com/ksiewert/BetaScan/wiki/Basic-Usage#explanation-of-parameters)). However, there's a small bug that is causing the header to also contain Beta1*, making it look like it should be a 3 column output file. I'm planning to release a new version of BetaScan soon in python3, and will fix this then. Thanks for catching this!

**Comment by ksiewert** [comment]
This issue should be corrected in the newest release. Let me know if you run into any issues with it.
