### ISSUE TITLE
chromosome information and beta score is none

### ISSUE THREAD

**Issue by DongmeiDai** [ksiewert/BetaScan#21]
Hi
I have two questions when I use the software.   
1. For the calculation of beta, if it is the whole genome, does it need to be calculated by chromosome? Because the output does not contain chromosome information, only location, should not be distinguishable? Or does this statistic just use the position, it doesn't need chromosome information?
2. The following error occurred while running, some beta score in the output is NONE. How can I solve it?
![image](https://github.com/ksiewert/BetaScan/assets/76728696/080d1afd-bf22-448d-a56e-f15d8493309f)

![image](https://github.com/ksiewert/BetaScan/assets/76728696/9cd3853d-4c7a-4a0d-ab2c-e907a3771028)

Thanks

**Comment by ksiewert** [comment]
Hello, thank you for your questions! 

1. You should run BetaScan on one chromosome at a time.
2. Can you send me the portion of your input file that causes the None errors? You can either post it here or e-mail it.

**Comment by DongmeiDai** [comment]
Thank you for your reply.
The first image is the input file that I reported an error
![image](https://github.com/ksiewert/BetaScan/assets/76728696/d1ede111-92b6-4afc-8c1b-62f28a0c68e1)
The initial error was this second image，and there is no output after the problematic line,like 51482094.
![image](https://github.com/ksiewert/BetaScan/assets/76728696/09e12577-74dd-4d71-b31d-1ca46f8cd60b)
Then I modified the script based on the error, the round function was removed, like third image. 
![image](https://github.com/ksiewert/BetaScan/assets/76728696/ee9e9e0f-c7b9-4127-a982-a1009615f837)
So the result is finally printed, but the line in question shows None.
![image](https://github.com/ksiewert/BetaScan/assets/76728696/ba401641-9c58-4da5-9d6f-1c5ad4e1d7e3)

**Comment by ksiewert** [comment]
Thank you! I don't see anything obviously wrong with the input file format, so I'll try to reproduce the error on my end. Could you send me the command you used to run BetaScan, so I know what parameters you used? If you could also send that section of the input file in a text format that would be helpful, so I can copy it into a text file.

**Comment by DongmeiDai** [comment]
Thank you, I've solved the problem. As long as I run one chromosome at a time , there are no errors.
