### ISSUE TITLE
Betascore within windows

### ISSUE THREAD

**Issue by willright28** [ksiewert/BetaScan#26]
Hi @ksiewert and all BetaScan users, 

Any clue to get the BetaScan value within a window, e.g., a genome region of 2000bp? One way I can think of is to choose the highest value of all the snp within the window.

Thanks!

**Comment by ksiewert** [comment]
Choosing the highest value within each window is a sensible approach. Just be aware that beta scores can be influenced by things like mutation rates, recombination rates and allele frequencies, which won't be stable across windows.
