### ISSUE TITLE
How to determine the threshold for sites with balancing selection?

### ISSUE THREAD

**Issue by wangzhx36** [ksiewert/BetaScan#27]
Hi,
I have run BetaScan successfully, but I don't know how to select a cutoff to judge whether one region has significant signal of balancing selection. Could you give me some advice?
Thanks for your help!

**Comment by ksiewert** [comment]
Hello, someone had a [very similar question](https://github.com/ksiewert/BetaScan/issues/1) a few years ago. Hopefully it helps!

**Comment by wangzhx36** [comment]
Hello,
Yes, I found that information and think it's very helpful for me. Thank you very much for your reply.
