### ISSUE TITLE
which ancestral individual should I choose?

### ISSUE THREAD

**Issue by congzhouczcz** [ksiewert/BetaScan#5]
Hey Katie，
 I want to known  if I have more than one ancestral individuals with different allele state (G and T), which individual should I choose?
Thanks,
Cong

**Comment by ksiewert** [comment]
This is a great question. As unsatisfying as it is, I would choose one individual to be the ancestral individual and use their alleles. The math assumes one outgroup individual. A single substitution or allele with a miscalled ancestral or derived allele will contribute much less to the Beta score than SNPs at highly similar frequencies do, so it shouldn't affect scores much.
