### ISSUE TITLE
TypeError: a float is required

### ISSUE THREAD

**Issue by coopergrace** [ksiewert/BetaScan#6]
Hi Katie,

I'm having a problem with running BetaScan. My command is:

`python BetaScan.py -i snps.beta.txt.gz -fold -o out.betascores.txt`

and the error I'm receiving:

`Traceback (most recent call last):
  File "BetaScan.py", line 613, in <module>
    main()
  File "BetaScan.py", line 602, in main
    output.write(str(loc)+"\t"+str(round(B,6))+"\n") #Remove thetas
TypeError: a float is required`

I'm using Python 2.7.17. I'd appreciate any suggestions you have please.

Cheers

**Comment by ksiewert** [comment]
Hello! Sorry for the delay. Github wasn't e-mailing me when people posted github issues, so I missed this. Without more information, it's hard to figure out what could be causing this. If it's still an issue, could you send me a subset of snps.beta.txt.gz that causes this issue, or add the following right before line 602 in the code and tell me what it outputs:
```
print loc
print B  
print type(loc)  
print type(B)
```

**Comment by xinhan2023** [comment]
-w. You can increase this score
