### ISSUE TITLE
question about input file

### ISSUE THREAD

**Issue by shiyi-pan** [ksiewert/BetaScan#7]
hi,I know that glactools can translate vcf into input file,but I can't install the glactools because the version of my computer,so I want to write a script to  translate vcf into input file,but I don't know the firt colum of the input file,can you tell me what's the meaning of 'the coordinate of each variant',is that the variant ID in vcf file?
thank you very much.

**Comment by ksiewert** [comment]
Hello, sorry for the delayed response! For some reason, github didn't e-mail me. The "coordinate of each variant" is the basepair position in the genome. This is used to select all SNPs in a given genomic window.
