### ISSUE TITLE
substitution data input format

### ISSUE THREAD

**Issue by josieparis** [ksiewert/BetaScan#8]
Hey Katie, 

Are you able to provide an example of the input file required for calculating B2? I'm generating the input files myself as I'm unable to use glactools (I'm using a non-model and the ancestral alleles have been called in a kinda homebrew way - i.e. are not in an epo file)

Thank you!

Josie

**Comment by ksiewert** [comment]
Hi Josie,

Yes, no problem! In the top panel on this page there's an example: https://github.com/ksiewert/BetaScan/wiki/Input-Format. The SNPs where the value of the 2nd column equals that of the 3rd are the substitutions. Let me know if this doesn't answer your question.


Best,
Katie
________________________________

**Comment by josieparis** [comment]
Ah of course! D'oh!! Thank you!
