### ISSUE TITLE
Unexpected results

### ISSUE THREAD

**Issue by benoitnabholz** [ksiewert/BetaScan#9]
Dear Katherine,

We recently used Betascan2 on the datasets generated by Singhal et al. 2015 (https://science.sciencemag.org/content/350/6263/928.abstract). This dataset is composed of 19 Zebra finch individuals sequenced at a coverage >10X.

When we applied Betascan2 (both the folded and unfolded version), I was surprised to see that the SNP with the highest Beta* statistics had, on average, a frequency that were **lower** than the rest of the genome (typically a frequence = 3% vs 5%).

Do you have any idea of what is going one? Do you have any advice on what should we check to see if the program is running correctly?

Thank-you for your help,
Benoit Nabholz

**Comment by ksiewert** [comment]
Hi Benoit,

Great question (and smart to check this)! At low allele frequencies some scans for balancing selection can be prone to false positives. I think you'll find the discussion of the -m parameter in this section of the BetaScan wiki<https://github.com/ksiewert/BetaScan/wiki/Basic-Usage#explanation-of-parameters> relevant. In humans we find setting the -m parameter to .15 to be sufficient to remove false positives. If zebrafish have a higher effective population size than humans, you may be able to go a bit lower than this. Hope this helps and let me know if you have any more questions.

Best,
Katie
________________________________
From: benoitnabholz ***@***.***>
Sent: Friday, April 2, 2021 10:09 AM
To: ksiewert/BetaScan ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ksiewert/BetaScan] Unexpected results (#9)


Dear Katherine,

We recently used Betascan2 on the datasets generated by Singhal et al. 2015 (https://science.sciencemag.org/content/350/6263/928.abstract<https://urldefense.proofpoint.com/v2/url?u=https-3A__science.sciencemag.org_content_350_6263_928.abstract&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=RCZkW2_0szgFcbgrJQDVb0JJbsAhoWepiDItwyb9mwg&m=WdutRlHsurzebXIFWhaQX3_2wCr5F-9yFTMZrQcpG8k&s=X5kmGGRUG82dFtOUT4Qgi0j7CI-ZV-c8S84oRnDQFFI&e=>). This dataset is composed of 19 Zebra finch individuals sequenced at a coverage >10X.

When we applied Betascan2 (both the folded and unfolded version), I was surprised to see that the SNP with the highest Beta* statistics had, on average, a frequency that were lower than the rest of the genome (typically a frequence = 3% vs 5%).

Do you have any idea of what is going one? Do you have any advice on what should we check to see if the program is running correctly?

Thank-you for your help,
Benoit Nabholz

**Comment by benoitnabholz** [comment]
Hi Katie,

Sorry for the late feedback. We applied the "-m" parameter and the results make much more sense now. The SNP with highest Beta* score have an average frequency close to 0.5 (unfolded version) which is significantly higher than the rest (~0.3).

Thank-you!
Benoit

**Comment by ksiewert** [comment]
Great to hear!
